"""
Validates all outputs and artifacts generated by the Customer Support Evaluation Pipeline.
"""

import json
import os
import sys

def run_validations() -> int:
    checks_passed = 0
    total_checks = 10

    print("=== Pipeline Artifact Validation ===")

    # --- Check 1: Required artifacts exist ---
    req_outputs = [
        "normalized_tickets.json", "draft_replies.json", "policy_checks.json",
        "llm_review.json", "human_overrides.json", "final_decisions.json",
        "evaluation_report.md", "llm_calls.jsonl"
    ]
    missing = [f for f in req_outputs if not os.path.isfile(os.path.join("outputs", f))]
    if missing:
        print(f"[FAIL] 1. Missing required artifacts in outputs/: {missing}")
    else:
        print("[PASS] 1. All required artifacts exist in outputs/")
        checks_passed += 1

    # --- Check 2: All JSON files are valid ---
    json_files = [f for f in req_outputs if f.endswith(".json")] + ["tickets.json", "policy.json"]
    bad_json = []
    parsed_data = {}
    for jf in json_files:
        path = os.path.join("outputs", jf) if jf in req_outputs else jf
        if os.path.isfile(path):
            try:
                with open(path, "r", encoding="utf-8") as f:
                    parsed_data[jf] = json.load(f)
            except Exception:
                bad_json.append(jf)
    
    if bad_json:
        print(f"[FAIL] 2. Invalid JSON files: {bad_json}")
    else:
        print("[PASS] 2. All JSON files are valid (parseable)")
        checks_passed += 1

    # --- Check 3: root files exist ---
    if not os.path.isfile("tickets.json") or not os.path.isfile("policy.json"):
        print("[FAIL] 3. tickets.json and policy.json must exist at project root")
    else:
        print("[PASS] 3. tickets.json and policy.json exist at project root")
        checks_passed += 1

    # --- Load JSONL calls for Checks 4-6 ---
    llm_calls = []
    calls_path = os.path.join("outputs", "llm_calls.jsonl")
    if os.path.isfile(calls_path):
        with open(calls_path, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    llm_calls.append(json.loads(line))

    # Determine expected ticket IDs
    expected_tids = set()
    norm_tickets = parsed_data.get("normalized_tickets.json", [])
    if isinstance(norm_tickets, list):
        expected_tids = {t.get("ticket_id") for t in norm_tickets if isinstance(t, dict)}

    # --- Check 4: draft_generation per ticket ---
    gen_tids = {c.get("ticket_id") for c in llm_calls if c.get("stage") == "draft_generation"}
    if expected_tids and expected_tids.issubset(gen_tids):
        print("[PASS] 4. llm_calls contains draft_generation for all tickets")
        checks_passed += 1
    else:
        missing_gen = expected_tids - gen_tids
        print(f"[FAIL] 4. Missing draft_generation calls for: {missing_gen}")

    # --- Check 5: llm_review per ticket ---
    rev_tids = {c.get("ticket_id") for c in llm_calls if c.get("stage") == "llm_review"}
    if expected_tids and expected_tids.issubset(rev_tids):
        print("[PASS] 5. llm_calls contains llm_review for all tickets")
        checks_passed += 1
    else:
        missing_rev = expected_tids - rev_tids
        print(f"[FAIL] 5. Missing llm_review calls for: {missing_rev}")

    # --- Check 6: Generation and review are separate ---
    sep_fail = any(isinstance(c.get("stage"), list) or c.get("stage") not in ["draft_generation", "llm_review"] for c in llm_calls)
    if sep_fail or not llm_calls:
        print("[FAIL] 6. Generation and review records overlap or are invalid")
    else:
        print("[PASS] 6. Generation and review are separate records")
        checks_passed += 1

    # --- Check 7: reply_sections_present is a list ---
    drafts = parsed_data.get("draft_replies.json", [])
    bad_drafts = [d for d in drafts if not isinstance(d.get("reply_sections_present"), list)]
    if bad_drafts or not drafts:
        print("[FAIL] 7. Some draft_replies lack a valid reply_sections_present list")
    else:
        print("[PASS] 7. Every draft_replies record has a reply_sections_present list")
        checks_passed += 1

    # --- Check 8: policy_risk in {"low", "medium", "high"} ---
    reviews = parsed_data.get("llm_review.json", [])
    bad_reviews = [r for r in reviews if r.get("policy_risk") not in {"low", "medium", "high"}]
    if bad_reviews or not reviews:
        print("[FAIL] 8. Some llm_review records have invalid policy_risk")
    else:
        print("[PASS] 8. Every llm_review record has a valid policy_risk")
        checks_passed += 1

    # --- Check 9: final_decisions auto_send logic ---
    decisions = parsed_data.get("final_decisions.json", [])
    overrides_data = parsed_data.get("human_overrides.json", {}).get("overrides", [])
    overrides_map = {o["ticket_id"]: o["override_route"] for o in overrides_data}
    
    bad_decisions = []
    for d in decisions:
        if d.get("final_route") == "auto_send":
            tid = d["ticket_id"]
            det_passed = d.get("deterministic_passed", False)
            overridden_to_auto = (overrides_map.get(tid) == "auto_send")
            
            # Must either natively pass deterministic, OR have been operator overridden to auto_send
            if not (det_passed or overridden_to_auto):
                bad_decisions.append(tid)
                
    if bad_decisions:
        print(f"[FAIL] 9. Invalid auto_send logic for tickets: {bad_decisions}")
    else:
        print("[PASS] 9. final_decisions auto_send logic holds true")
        checks_passed += 1

    # --- Check 10: evaluation_report.md contains all headers ---
    req_headers = [
        "## Summary",
        "## Auto-send candidates",
        "## Human review required",
        "## Common failure patterns",
        "## Improvement suggestions"
    ]
    report_path = os.path.join("outputs", "evaluation_report.md")
    missing_headers = []
    if os.path.isfile(report_path):
        with open(report_path, "r", encoding="utf-8") as f:
            content = f.read()
            missing_headers = [h for h in req_headers if h not in content]
    else:
        missing_headers = req_headers
        
    if missing_headers:
        print(f"[FAIL] 10. evaluation_report.md is missing headers: {missing_headers}")
    else:
        print("[PASS] 10. evaluation_report.md contains all required headers")
        checks_passed += 1

    # --- Final Result ---
    print(f"\nValidation: {checks_passed}/{total_checks} checks passed.")
    return 0 if checks_passed == total_checks else 1

if __name__ == "__main__":
    sys.exit(run_validations())
